import fs from 'node:fs';
import path from 'node:path';
import MarkdownIt from 'markdown-it';

const root=process.cwd();
const out=path.resolve(root,'.site');
if(out!==path.join(root,'.site')||out===root)throw Error('Unsafe site output directory');
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
const base=process.env.SITE_BASE??'/employee-agent-platform-docs/';
if(!/^\/(?:[a-zA-Z0-9_-]+\/)*$/.test(base))throw Error('SITE_BASE must be a slash-delimited path');
const origin='https://agents-foundry.github.io';
const repo='https://github.com/Agents-Foundry/employee-agent-platform-docs';
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const write=(p,s)=>{const target=path.join(out,p);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,s);};
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]);
const paths=[...fs.readdirSync(root).filter(p=>p.endsWith('.md')),...['docs','examples'].flatMap(d=>walk(path.join(root,d)).filter(p=>p.endsWith('.md')).map(p=>path.relative(root,p).replaceAll('\\','/')))];
const htmlPath=p=>p==='README.md'?'index.html':p.endsWith('/README.md')?p.replace(/README\.md$/,'index.html'):p.replace(/\.md$/,'.html');
const slug=s=>s.toLowerCase().replace(/<[^>]+>/g,'').replace(/[^\p{L}\p{N}_\-\s]/gu,'').replace(/\s/g,'-');
const groupLabels={'getting-started':'Getting started',concepts:'Core concepts',architecture:'Architecture',agents:'Agent manifests',admin:'Administration',employee:'Employee workspace',developer:'Development',runtime:'Agent runtime',execution:'Execution runtime',integrations:'Integrations',security:'Security',api:'API reference','data-model':'Data model',deployment:'Deployment',operations:'Operations',qa:'Testing & readiness','use-cases':'Role walkthroughs',reference:'Reference',adr:'Decision records',roadmap:'Architecture gaps',contributing:'Maintaining docs'};
const groupOf=p=>p.startsWith('docs/')?p.split('/')[1]:p.startsWith('examples/')?'examples':'project';
const pages=paths.map(p=>({path:p,url:base+htmlPath(p),group:groupOf(p),source:fs.readFileSync(p,'utf8')}));
for(const p of pages)p.title=p.source.match(/^#\s+(.+)$/m)?.[1]??p.path;
const titles=new Map(pages.map(p=>[p.path,p.title]));
function link(url,current){if(/^[a-z][a-z\d+.-]*:/i.test(url)||url.startsWith('//')||url.startsWith('#'))return url;const [location,hash]=url.split('#');const resolved=path.posix.normalize(path.posix.join(path.posix.dirname(current),location));if(resolved.startsWith('../'))throw Error(`Link leaves project: ${current}: ${url}`);return base+(titles.has(resolved)?htmlPath(resolved):resolved)+(hash?'#'+hash:'');}
const md=new MarkdownIt({html:false,linkify:false,typographer:false});
const normalLink=md.renderer.rules.link_open??((tokens,i,options,env,self)=>self.renderToken(tokens,i,options));
md.renderer.rules.link_open=(tokens,i,options,env,self)=>{tokens[i].attrSet('href',link(tokens[i].attrGet('href'),env.path));return normalLink(tokens,i,options,env,self);};
md.renderer.rules.image=(tokens,i,options,env,self)=>{tokens[i].attrSet('src',link(tokens[i].attrGet('src'),env.path));tokens[i].attrSet('loading','lazy');return self.renderToken(tokens,i,options);};
md.renderer.rules.heading_open=(tokens,i,options,env,self)=>{const title=tokens[i+1].content;const id=slug(title);const count=env.headings.get(id)||0;env.headings.set(id,count+1);const unique=id+(count?'-'+count:'');tokens[i].attrSet('id',unique);if(tokens[i].tag==='h2'||tokens[i].tag==='h3')env.toc.push({id:unique,title,depth:tokens[i].tag});return self.renderToken(tokens,i,options);};
const normalFence=md.renderer.rules.fence;
md.renderer.rules.fence=(tokens,i,options,env,self)=>{const token=tokens[i];if(token.info==='mermaid'){env.hasMermaid=true;return `<figure class="diagram"><figcaption>Architecture diagram <button class="diagram-source" type="button" aria-expanded="false">View source</button></figcaption><div class="mermaid" data-source="${escape(token.content)}" aria-label="Architecture diagram"><pre>${escape(token.content)}</pre></div><pre class="diagram-code" hidden><code>${escape(token.content)}</code></pre></figure>`;}const body=normalFence(tokens,i,options,env,self);return `<div class="code-block"><div class="code-toolbar"><span>${escape(token.info||'text')}</span><button class="copy-code" type="button" aria-label="Copy code">Copy</button></div>${body}</div>`;};
md.renderer.rules.table_open=()=>'<div class="table-scroll" tabindex="0" role="region" aria-label="Scrollable reference table"><table>\n';md.renderer.rules.table_close=()=>'</table></div>\n';
function sidebar(page){let s=`<a class="sidebar-home ${page.path==='README.md'?'current':''}" href="${base}">Overview</a><a class="sidebar-home ${page.path==='docs/README.md'?'current':''}" href="${base}docs/index.html">All documentation</a>`;for(const [group,label] of Object.entries({...groupLabels,examples:'Examples',project:'Project resources'})){const list=pages.filter(p=>p.group===group&&p.path!=='README.md'&&p.path!=='docs/README.md').sort((a,b)=>(a.path.endsWith('README.md')?-1:b.path.endsWith('README.md')?1:a.title.localeCompare(b.title)));if(!list.length)continue;s+=`<details ${page.group===group||group==='getting-started'?'open':''}><summary>${label}<span>${list.length}</span></summary><div>${list.map(p=>`<a href="${p.url}" ${p.path===page.path?'aria-current="page"':''}>${escape(p.title.replace(/^ADR \d+: /,''))}</a>`).join('')}</div></details>`;}return s;}
const search=[];
for(const page of pages){const env={path:page.path,headings:new Map(),toc:[],hasMermaid:false};const body=md.render(page.source,env);const excerpt=page.source.split('\n').find(line=>line.length>80&&!line.startsWith('|')&&!line.startsWith('**'))??page.title;const group=groupLabels[page.group]??(page.group==='examples'?'Examples':'Project');const nav=sidebar(page);const toc=env.toc.map(h=>`<a class="${h.depth==='h3'?'toc-sub':''}" href="#${h.id}">${escape(h.title.replaceAll('`','').replaceAll('*',''))}</a>`).join('');
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>${escape(page.title)} · Agents Foundry Docs</title><meta name="description" content="${escape(excerpt.slice(0,180))}"><link rel="canonical" href="${origin+page.url}"><link rel="icon" href="${base}assets/favicon.svg" type="image/svg+xml"><script src="${base}assets/preferences.js"></script><link rel="stylesheet" href="${base}assets/site.css"><script src="${base}assets/site.js" defer></script></head><body data-base="${base}" data-mermaid="${env.hasMermaid}"><a class="skip-link" href="#main-content">Skip to content</a><header class="site-header"><a class="brand" href="${base}"><span class="brand-mark">AF</span><span>Agents Foundry <span class="brand-docs">/ Docs</span></span></a><div class="header-controls"><button class="search-trigger" type="button" aria-label="Search documentation"><span aria-hidden="true">⌕</span> <span>Search documentation</span><kbd>Ctrl K</kbd></button><a class="github-link" href="${repo}">GitHub ↗</a><button class="theme-toggle" type="button" aria-label="Switch color theme">◐</button><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="sidebar" aria-label="Toggle documentation menu">☰</button></div></header><div class="site-layout"><aside id="sidebar" class="sidebar" aria-label="Documentation navigation"><nav>${nav}</nav><div class="sidebar-foot"><span class="status-dot"></span>Source-backed documentation<br><small>Platform baseline · 9e7ec4e</small></div></aside><div class="sidebar-backdrop" hidden></div><main id="main-content" tabindex="-1"><div class="page-meta"><span>${escape(group)}</span><a href="${repo}/blob/main/${page.path}">View Markdown ↗</a></div><article class="prose ${page.path==='README.md'?'home':''}">${body}</article><footer class="page-footer"><a href="${repo}/edit/main/${page.path}">Suggest an improvement ↗</a><a href="#main-content">Back to top ↑</a><p>Implementation status and evidence are documented per guide. This site is built from the documentation repository.</p></footer></main><aside class="toc" aria-label="On this page"><strong>On this page</strong><nav>${toc||'<span>No subheadings</span>'}</nav></aside></div><dialog class="search-dialog" aria-labelledby="search-title"><div class="search-top"><label class="sr-only" id="search-title" for="search-input">Search documentation</label><input id="search-input" type="search" placeholder="Search guides, APIs, concepts…" autocomplete="off" maxlength="200"><button class="search-close" type="button" aria-label="Close search">Esc</button></div><div id="search-results" aria-live="polite"><p class="search-hint">Search across all ${pages.length} documentation pages.</p></div><div class="search-footer">Search runs in your browser. <span>Esc to close</span></div></dialog></body></html>`;
write(htmlPath(page.path),html);search.push({title:page.title,url:page.url,group,text:body.replace(/<[^>]*>/g,' ').replace(/&(?:amp|lt|gt|quot);/g,' ').replace(/\s+/g,' ').trim()});}
write('assets/search-index.json',JSON.stringify(search));
for(const name of ['site.css','site.js','preferences.js','favicon.svg'])fs.copyFileSync(path.join(root,'site',name),path.join(out,'assets',name));
for(const dir of ['examples','reference-data'])for(const file of walk(path.join(root,dir)).filter(p=>/\.(json|sql)$/.test(p))){const target=path.relative(root,file);fs.mkdirSync(path.dirname(path.join(out,target)),{recursive:true});fs.copyFileSync(file,path.join(out,target));}
fs.copyFileSync('source-inventory.json',path.join(out,'source-inventory.json'));
const mermaidRoot=path.join(root,'node_modules/mermaid/dist');const vendor=path.join(out,'assets/mermaid');fs.mkdirSync(vendor,{recursive:true});fs.copyFileSync(path.join(mermaidRoot,'mermaid.esm.min.mjs'),path.join(vendor,'mermaid.esm.min.mjs'));
fs.copyFileSync(path.join(root,'node_modules/mermaid/LICENSE'),path.join(vendor,'LICENSE'));
for(const file of walk(path.join(mermaidRoot,'chunks/mermaid.esm.min')).filter(f=>f.endsWith('.mjs'))){const target=path.join(vendor,path.relative(mermaidRoot,file));fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(file,target);}
write('.nojekyll','');write('404.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found · Agents Foundry</title><link rel="stylesheet" href="${base}assets/site.css"><main class="not-found"><span class="brand-mark">AF</span><h1>This page isn’t here.</h1><p>Find your guide in the documentation index or search the platform docs.</p><a href="${base}docs/index.html">Browse documentation →</a></main></html>`);
write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin+base}sitemap.xml\n`);write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p=>`<url><loc>${origin+p.url}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${pages.length} documentation pages with local search and Mermaid assets in .site (${base}).`);
